#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Customize to your needs...

# source any extra initialization scripts
INITDIR=$HOME/.etc/init

for i in $INITDIR/* $INITDIR/zsh/*; do
  if [ -f $i -a -x $i ]; then
    source $i
  fi
done
